name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Actualizar a v3

      - name: Install Node.js
        uses: actions/setup-node@v3 # Actualizar a v3
        with:
          node-version: '20' # Usar Node.js 20

      - name: Install Surge
        run: npm install --global surge

      - name: Deploy to Surge
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        run: surge --project ./ --domain tu-dominio.surge.sh

